# Generated by Django 4.2 on 2023-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_collection_created_at_collection_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
