# Generated by Django 4.2 on 2023-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_created_at_collection_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='views',
            field=models.IntegerField(default='0'),
        ),
    ]
