# Generated by Django 4.2 on 2023-05-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_item_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha2_code', models.CharField(max_length=2)),
                ('alpha3_code', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PF', 'Proof'), ('PL', 'Proof-like'), ('BU', 'Brilliant Uncirculated'), ('UNC', 'Uncirculated'), ('AU+', 'Choice Almost/About Uncirculated'), ('AU', 'Almost/About Uncirculated'), ('XF+', 'Choice Extremely Fine'), ('XF', 'Extremely Fine'), ('VF+', 'Choice Very Fine'), ('VF', 'Very Fine'), ('F', 'Fine'), ('VG', 'Very Good'), ('G', 'Good'), ('AG', 'Almost/About Good'), ('FA', 'Fair'), ('PR', 'Poor')], default='VF', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
