# Generated by Django 4.2 on 2023-05-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
