# Generated by Django 4.2 on 2023-05-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_country_name_alter_country_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(),
        ),
    ]
