# Generated by Django 4.2 on 2023-05-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_country_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
