# Generated by Django 4.2 on 2023-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alpha2_code', models.CharField(max_length=2)),
                ('alpha3_code', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField(default='0')),
            ],
        ),
    ]
