# Generated by Django 4.2 on 2023-05-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2_code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3_code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=100),
        ),
    ]
