# Generated by Django 4.2 on 2023-05-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_country_alpha2_code_alter_country_alpha3_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
    ]
