# Generated by Django 4.2 on 2023-05-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_country_capital_remove_country_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='alpha2_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='alpha3_code',
        ),
    ]
