# Generated by Django 4.2 on 2023-05-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
