# Generated by Django 4.2 on 2023-05-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
