# Generated by Django 4.2 on 2023-05-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_photo',
            field=models.ImageField(upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='obverse',
            field=models.ImageField(upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reverse',
            field=models.ImageField(upload_to='item_images'),
        ),
    ]
