# Generated by Django 4.2 on 2023-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_item_extra_photo_alter_item_obverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('coin', 'Coin'), ('banknote', 'Banknote'), ('pin', 'Pin'), ('videogame', 'Videogame'), ('post_stamp', 'Post Stamp'), ('magazine', 'Magazine'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
