# Generated by Django 4.2 on 2023-05-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
