# Generated by Django 4.2 on 2023-05-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_item_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='CBRF',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='ISSN',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='WWC',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='catalog_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_publish',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='extra_photo',
            field=models.ImageField(blank=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='obverse',
            field=models.ImageField(blank=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preservation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.preservation'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='reverse',
            field=models.ImageField(blank=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
