# Generated by Django 4.2 on 2023-05-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_item_country_alter_item_preservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
