# Generated by Django 4.2 on 2023-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_item_weight_alter_item_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
