# Generated by Django 4.2 on 2023-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_item_height_alter_item_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_publish',
            field=models.DateField(blank=True, default=''),
        ),
    ]
