# Generated by Django 4.2 on 2023-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_item_date_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
