# Generated by Django 4.2 on 2023-05-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_item_cbrf_alter_item_issn_alter_item_wwc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='CBRF',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ISSN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='WWC',
        ),
        migrations.RemoveField(
            model_name='item',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_publish',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extra_photo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='obverse',
        ),
        migrations.RemoveField(
            model_name='item',
            name='preservation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reverse',
        ),
        migrations.RemoveField(
            model_name='item',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width',
        ),
        migrations.RemoveField(
            model_name='item',
            name='year',
        ),
    ]
