# Generated by Django 4.2 on 2023-05-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_item_cbrf_item_issn_item_wwc_item_catalog_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_publish',
        ),
    ]
