# Generated by Django 4.2 on 2023-05-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_item_date_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='CBRF',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ISSN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='WWC',
        ),
        migrations.RemoveField(
            model_name='item',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width',
        ),
        migrations.RemoveField(
            model_name='item',
            name='year',
        ),
    ]
