# Generated by Django 4.2 on 2023-05-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_item_cbrf_item_issn_item_wwc_item_catalog_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='preservation',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='trade',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
