# Generated by Django 4.2 on 2023-05-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_item_country_remove_item_preservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='visibility',
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='preservation',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
