# Generated by Django 4.2 on 2023-05-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_item_trade_remove_item_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trade',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
