# Generated by Django 4.2 on 2023-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_item_trade_item_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
