# Generated by Django 4.2 on 2023-05-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_item_date_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_publish',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
