# Generated by Django 4.2 on 2023-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_item_date_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='obverse',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
