# Generated by Django 4.2 on 2023-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_item_obverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='obverse',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
