# Generated by Django 4.2 on 2023-05-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_item_obverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='CBRF',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ISSN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='WWC',
        ),
        migrations.RemoveField(
            model_name='item',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_publish',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='preservation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width',
        ),
        migrations.RemoveField(
            model_name='item',
            name='year',
        ),
    ]
