# Generated by Django 4.2 on 2023-05-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_item_cbrf_item_issn_item_wwc_item_catalog_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='market',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
