# Generated by Django 4.2 on 2023-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_item_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
