# Generated by Django 4.2 on 2023-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_item_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
