# Generated by Django 4.2 on 2023-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_item_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_from', models.IntegerField()),
                ('user_to', models.IntegerField()),
                ('items_from', models.JSONField()),
                ('items_to', models.JSONField()),
                ('status', models.BooleanField(null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
