# Generated by Django 4.2 on 2023-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_trade_date_create_alter_trade_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.IntegerField()),
                ('recipient', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.IntegerField()),
                ('recipient', models.IntegerField()),
                ('body', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
