# Generated by Django 4.2 on 2023-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
