# Generated by Django 4.2 on 2023-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_trade_date_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='chat',
            name='body',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
