# Generated by Django 4.2 on 2023-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_delete_message_chat_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='recipient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
