# Generated by Django 4.2 on 2023-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_chat_recipient_alter_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='recipient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
