# Generated by Django 4.2 on 2023-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_alter_chat_recipient_alter_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='recipient',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
